version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8880:80"
      - "8881:443"
    restart: always
    secrets:
      - source: nginx_internal_cert
        target: /certs/cert_internal.crt
      - source: nginx_internal_key
        target: /certs/key_internal.key
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
    networks:
      - jenkins
    extra_hosts:
    - "host.docker.internal:host-gateway"

  jenkins:
    container_name: jenkins-master
    build:
      context: ./master
      dockerfile: Dockerfile
      args:
         HOST_UID: ${HOST_UID}
         HOST_GID: ${HOST_GID}
    env_file:
      - .env
    restart: unless-stopped
    user: jenkins
    volumes:
      - jenkins_data:/var/jenkins_home:rw
    networks:
      - jenkins

  docker-slave:
    container_name: jenkins-docker-slave
    build:
      context: ./agents/docker
      args:
         HOST_UID: ${HOST_UID}
         HOST_GID: ${HOST_GID}
    privileged: true
    user: jenkins
    restart: unless-stopped
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    volumes:
      - ${HOST_DOCKER}:/var/run/docker.sock
      - docker_slave:/home/jenkins
    networks:
      - jenkins

  postman-slave:
    container_name: jenkins-postman-slave
    build:
      context: ./agents/postman
      dockerfile: Dockerfile
    volumes:
      - postman_newman:/etc/newman
      - postman_slave:/home/jenkins
    privileged: true
    restart: unless-stopped
    user: jenkins
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    networks:
      - jenkins

  # dotnet-slave:
  #   container_name: jenkins-dotnet-slave
  #   build:
  #     context: ./agents/dotnet
  #     dockerfile: Dockerfile
  #   privileged: true
  #   restart: unless-stopped
  #   user: jenkins
  #   expose:
  #     - 22
  #   environment:
  #     - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
  #   networks:
  #     - jenkins

secrets:
  nginx_internal_cert:
    file: secrets/certs/nginx-selfsigned.crt
  nginx_internal_key:
    file: secrets/certs/nginx-selfsigned.key
  nginx_conf:
    file: nginx/conf/nginx.conf

volumes:
   jenkins_data:
   docker_slave:
   postman_slave:
   postman_newman:

networks:
   jenkins: